
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: nugetProjects
    type: object
    default:
      - Xamarin.FluentInjector

stages:
  - stage: 'Packing'
    displayName: 'Packing into nugets'

    jobs:
      - job: 'Builds'
        displayName: 'Building projects to pack'
        steps:

        - ${{ each project in parameters.nugetProjects }}:
          - script: 'dotnet build -c RELEASE'
            displayName: Building for ${{ project }}
            workingDirectory: src/${{ project }}

      - job: 'Pack'
        dependsOn:'Builds'
        condition: succeeded()
        displayName: 'Packing build projects'
        steps:

        - ${{ each project in parameters.nugetProjects }}:
          - script: 'dotnet pack -c RELEASE --no-build -p:PackageVersion 0.0.$(Build.BuildId)'
            displayName: Packing for ${{ project }}
            workingDirectory: src/${{ project }}


        