
trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: nugetProjects
    type: object
    default:
      - Xamarin.FluentInjector

stages:
  - stage: 'Packing'
    displayName: 'Packing into nugets'

    jobs:
      - job: 'Pack'
        displayName: 'Packing build projects'
        steps:

        - ${{ each project in parameters.nugetProjects }}:
          - script: 'dotnet pack -c RELEASE -p:PackageVersion=0.0.$(Build.BuildId)'
            displayName: Packing for ${{ project }}
            workingDirectory: src/${{ project }}


        